var classes = [
    {
        "name": "Process",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "processData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 27,
        "vocabulary": 13,
        "volume": 99.91,
        "difficulty": 2.7,
        "effort": 269.76,
        "level": 0.37,
        "bugs": 0.03,
        "time": 15,
        "intelligentContent": 37,
        "number_operators": 9,
        "number_operands": 18,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 6,
        "loc": 28,
        "lloc": 22,
        "mi": 88.64,
        "mIwoC": 55.77,
        "commentWeight": 32.86,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "\\",
        "pageRank": 0.33,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Calculate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "calculateTax",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateBonus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 48,
        "vocabulary": 16,
        "volume": 192,
        "difficulty": 7.8,
        "effort": 1497.6,
        "level": 0.13,
        "bugs": 0.06,
        "time": 83,
        "intelligentContent": 24.62,
        "number_operators": 22,
        "number_operands": 26,
        "number_operators_unique": 6,
        "number_operands_unique": 10,
        "cloc": 6,
        "loc": 30,
        "lloc": 24,
        "mi": 84.9,
        "mIwoC": 52.96,
        "commentWeight": 31.94,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7,
        "relativeSystemComplexity": 7,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 14,
        "totalSystemComplexity": 14,
        "package": "\\",
        "pageRank": 0.33,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Complex",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "complexFunction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 48,
        "vocabulary": 21,
        "volume": 210.83,
        "difficulty": 26,
        "effort": 5481.61,
        "level": 0.04,
        "bugs": 0.07,
        "time": 305,
        "intelligentContent": 8.11,
        "number_operators": 22,
        "number_operands": 26,
        "number_operators_unique": 14,
        "number_operands_unique": 7,
        "cloc": 3,
        "loc": 25,
        "lloc": 22,
        "mi": 79.07,
        "mIwoC": 53.5,
        "commentWeight": 25.56,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 8,
        "relativeSystemComplexity": 8,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "\\",
        "pageRank": 0.33,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]